# Jenkins/Dockerfile
FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add jenkins to docker group if it exists, else create it
RUN if ! getent group docker; then groupadd -g 999 docker; fi && \
    usermod -aG docker jenkins

RUN apt-get update && \
    apt-get install -y curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    ln -s /usr/local/bin/kubectl /usr/bin/kubectl && \
    rm kubectl

USER jenkins

# Copy plugin list and install plugins automatically
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Expose Jenkins web and agent ports
EXPOSE 8080 50000
