apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
        - name: cloud-config
          # This will be overridden by Jenkins with actual tag (e.g., pr-123)
          image: juanse201/cloud-config:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery-container:8761/eureka/"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
spec:
  type: ClusterIP
  ports:
    - port: 9296
      targetPort: 9296
  selector:
    app: cloud-config