apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          # This will be overridden by Jenkins with actual tag (e.g., pr-123)
          image: juanse201/favourite-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296/"
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
spec:
  type: ClusterIP
  ports:
    - port: 8800
      targetPort: 8800
  selector:
    app: favourite-service