apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          # This will be overridden by Jenkins with actual tag (e.g., pr-123)
          image: juanse201/product-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery-container:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config-container:9296/"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "product-service-container"
            - name: EUREKA_INSTANCE_NON_SECURE_PORT
              value: "8500"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8500
  selector:
    app: product-service