apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          # This will be overridden by Jenkins with actual tag (e.g., pr-123)
          image: juanse201/user-service-ecommerce-boot:dev
          ports:
            - containerPort: 8700
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery-container:8761/eureka/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config-container:9296/"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
    - port: 8700
      targetPort: 8700
  selector:
    app: user-service